REM   Script: Q2
REM   Q2

--using https://livesql.oracle.com
DROP VIEW SYMPFREQ;

CREATE VIEW SYMPFREQ (SYMP_ID,SYMP_ID_FREQ) AS 
SELECT SYMPTOM_ID, COUNT(SYMPTOM_ID) 
FROM SYMPTOM 
GROUP BY SYMPTOM_ID 
ORDER BY COUNT(SYMPTOM_ID) DESC;

SELECT SYMP_ID 
FROM SYMPFREQ 
WHERE SYMP_ID_FREQ = (SELECT MAX(SYMP_ID_FREQ) FROM SYMPFREQ);

