REM   Script: Q3
REM   Q3

--using https://livesql.oracle.com
DROP VIEW FLOOR;

CREATE VIEW FLOOR (FCOUNT, FNUMBER) AS 
SELECT COUNT(EMPLOYEE.FLOOR_NUMBER) , EMPLOYEE.FLOOR_NUMBER 
FROM EMPLOYEE,TEST_TABLE 
WHERE (EMPLOYEE.EMPLOYEE_ID=TEST_TABLE.EMPLOYEE_ID) AND (TEST_TABLE.TEST_RESULT='Positive')  
GROUP BY EMPLOYEE.FLOOR_NUMBER  
ORDER BY COUNT(EMPLOYEE.FLOOR_NUMBER) DESC;

SELECT FNUMBER 
FROM FLOOR 
WHERE FCOUNT = (SELECT MAX(FCOUNT) FROM FLOOR);

